name: Building and Pushed
on:
  schedule:
       - cron: "* 23 * * *"   
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/main.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Determine tag
        run: | 
          cd /tmp 
          git -c http.sslVerify=false clone --depth 1 --branch stable https://github.com/taigaio/taiga-back.git taiga-back
          cd taiga-back
          export TAG=`git tag`
          echo "::set-env name=TAG::$TAG"
          
      - name: Check $TAG
        run: echo $TAG
        
      - name: Build and push   
        uses: docker/build-push-action@v1
        with:
          path: . 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nemonik/taiga
          tags: latest, ${{ env.TAG }}
