on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/main.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build and push   
        uses: docker/build-push-action@v1
        with:
          path: . 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nemonik/taiga
          tag_with_ref: true
